### PR TITLE
Metrics for firing regularity based on ISI.

### PR DESCRIPTION
**Pull request by przemyslawj**
Implemented metrics:
- local variation coefficient
- Spearman's rank correlation coefficient
- estimate of gamma distribution

### CODE REVIEW

**Comment by przemyslawj** [comment]
After this is reviewed I'm planning to add some examples to vignettes showing how to use the new metrics.

**Review by sje30 — APPROVED** [review]

**Comment by sje30** [comment]
thank you.

**Comment by sje30** [comment]
ah, can you fix these warnings, when I try to buid:

```
build()
...
Warning: /tmp/Rtmppa8f0j/Rbuilddd2a470299cf/sjemea/man/isi.local.variation.Rd:7: unknown macro '\sum'
Warning: /tmp/Rtmppa8f0j/Rbuilddd2a470299cf/sjemea/man/isi.spearman.rank.corr.Rd:22: unknown macro '\sum'
Warning: /tmp/Rtmppa8f0j/Rbuilddd2a470299cf/sjemea/man/isi.spearman.rank.corr.Rd:23: unknown macro '\sum'
```

**Comment by przemyslawj** [comment]
Sure, will do. I forgot to check that this latex notation doesn't cause any issues in the documentation. Thank you for the review!

**Pull request merged**
